# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
