# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-27 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tipologia',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature', 'Feature')], default='', max_length=50),
        ),
    ]
