# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_post_tipologia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='answer',
            field=models.TextField(default='', max_length=500),
        ),
    ]
