# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190628_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='answer',
            field=models.TextField(default='', max_length=100000),
        ),
    ]
