# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190624_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
