# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190628_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('To-Do', 'To-Do'), ('Done', 'Done')], default='', max_length=50),
        ),
    ]
