# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190628_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='solution_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
