# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-24 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
