# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-28 23:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_post_my_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='issue',
        ),
    ]
